package com.tly.mango.service;

import com.tly.mango.entity.SysRoleDept;

import java.util.List;

public interface SysRoleDeptService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_dept
     *
     * @mbg.generated Fri Apr 10 14:27:02 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_dept
     *
     * @mbg.generated Fri Apr 10 14:27:02 CST 2020
     */
    int insert(SysRoleDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_dept
     *
     * @mbg.generated Fri Apr 10 14:27:02 CST 2020
     */
    SysRoleDept selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_dept
     *
     * @mbg.generated Fri Apr 10 14:27:02 CST 2020
     */
    List<SysRoleDept> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_dept
     *
     * @mbg.generated Fri Apr 10 14:27:02 CST 2020
     */
    int updateByPrimaryKey(SysRoleDept record);
}
