package com.tly.mango.service;

import com.tly.mango.entity.SysRoleMenu;

import java.util.List;

public interface SysRoleMenuService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu
     *
     * @mbg.generated Fri Apr 10 14:27:50 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu
     *
     * @mbg.generated Fri Apr 10 14:27:50 CST 2020
     */
    int insert(SysRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu
     *
     * @mbg.generated Fri Apr 10 14:27:50 CST 2020
     */
    SysRoleMenu selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu
     *
     * @mbg.generated Fri Apr 10 14:27:50 CST 2020
     */
    List<SysRoleMenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu
     *
     * @mbg.generated Fri Apr 10 14:27:50 CST 2020
     */
    int updateByPrimaryKey(SysRoleMenu record);
}
