package com.tly.mango.service;

import com.tly.mango.entity.SysUserRole;

import java.util.List;

public interface SysUserRoleService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Fri Apr 10 14:29:08 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Fri Apr 10 14:29:08 CST 2020
     */
    int insert(SysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Fri Apr 10 14:29:08 CST 2020
     */
    SysUserRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Fri Apr 10 14:29:08 CST 2020
     */
    List<SysUserRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Fri Apr 10 14:29:08 CST 2020
     */
    int updateByPrimaryKey(SysUserRole record);
}
